Revert "When a JSON-RPC connection is closed, send an error response to all outstanding requests" (#1706)
Reverts swiftlang/sourcekit-lsp#1688

This seems to be breaking toolchain builds:

```
JSONRPCConnection.swift:168:35: error: reference to property 'outstandingRequests' in closure
requires explicit use of 'self' to make capture semantics explicit
        for outstandingRequest in outstandingRequests.values {
```

https://ci.swift.org/job/swift-PR-toolchain-macos/1519/console