Must include full path to `Block.h`
`swift build -Xcxx -I/usr/lib/swift` fails on Linux w/

```
.../sourcekit-lsp/.build/checkouts/indexstore-db/lib/CIndexStoreDB/CIndexStoreDB.cpp:20:10: fatal error: 'Block.h' file not found
#include <Block.h>
         ^~~~~~~~~
1 error generated.
```

Need to add `-I/usr/lib/swift/Block` to make it work. Confirmed via https://github.com/apple/indexstore-db