Implement `sourcekit-lsp --version` option
Currently `sourcekit-lsp --version` is an invalid option, which makes it harder to debug issues with SourceKit-LSP, as one can't even easily know which version is installed:

```
❯ sourcekit-lsp --version
Error: Unknown option '--version'
```