Don’t build SourceKitLSPPackageTests in build-script-helper’s build action
Building SourceKitLSPPackageTests with cross-compilation enabled fails with
```
error: Could not find target named 'mypackagePackageTests_586B622B321A3B86_PackageProduct'
error: fatalError
```

For testing, we work around this by disabling cross-compilation. This is not possible for building, so we need to explicitly build all products.